export const UPDATE_LINK =  "UPDATE_LINK";
export const UPDATE_FORMAT =  "UPDATE_FORMAT";

export const ADD_SONG = "ADD_SONG";
export const DELETE_SONG = "DELETE_SONG";
export const UPDATE_SONG = "UPDATE_SONG";

export const BEGIN_DOWNLOAD_SONG_INFO = "BEGIN_DOWNLOAD_SONG_INFO";
export const DOWNLOAD_SONG = "DOWNLOAD_SONG";
export const DOWNLOAD_SONG_INFO_SUCCESS = "DOWNLOAD_SONG_INFO_SUCCESS";
export const DOWNLOAD_SONG_INFO_ERROR = "DOWNLOAD_SONG_INFO_ERROR";